 #This is the name of worflow
name: cicd

# manual click deliver
on:
  workflow_dispatch:
    inputs:
      environment:
        description: This is the environment where is the workflow runs
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
          - prod
          - staging

jobs:

  code:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code
        run: echo "Code clone ho gya"
  build:
    needs: code
    runs-on: ubuntu-latest
    steps:
      - name: Build docker container
        run: echo "Docker container build ho gya"
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: test the container
        run: echo "Test done ho gya"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on server
        run: echo "Deploy ho gya"
